## **How Do Convolutional Layers Work in Deep Learning Neural Networks**

https://machinelearningmastery.com/convolutional-layers-for-deep-learning-neural-networks/
  
**Keras: set_weights(weight):**
- weights: a list of Numpy arrays. The number of arrays and their shape must match number of the dimensions of the weights of the layer (i.e. it should match the output of get_weights).

**Example of 1D Convolution Layer**
- Create dataset
  - Dimensions:
    - Dim 1: input sample (1)
    - Dim 2: Length of each sample (8)
    - Dim 3: Number of channels (1)
- Define a vertical line filter/detector
- Apply to dataset

In [8]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv1D

# define input data
data = asarray([0, 0, 0, 1, 1, 0, 0, 0])
data = data.reshape(1, 8, 1)

print(data)

[[[0]
  [0]
  [0]
  [1]
  [1]
  [0]
  [0]
  [0]]]


In [9]:
# create model
model = Sequential()
model.add(Conv1D(1, 3, input_shape=(8, 1)))

In [11]:
# define a vertical line detector
weights = [asarray([[[0]],[[1]],[[0]]]), asarray([0.0])]
# store the weights in the model
model.set_weights(weights)

# confirm they were stored
print(model.get_weights())

[array([[[0.]],

       [[1.]],

       [[0.]]], dtype=float32), array([0.], dtype=float32)]


In [12]:
# apply filter to input data
yhat = model.predict(data)
print(yhat)

[[[0.]
  [0.]
  [1.]
  [1.]
  [0.]
  [0.]]]


**Example of 2D Convolution Layer**
- Create dataset
  - Dimensions:
    - Dim 1: number of input sample (1)
    - Dim 2: Length of each row of sample (8)
    - Dim 3: Length of each column of sample (8)
    - Dim 4: Number of channels (1)
- Define a vertical line filter/detector
- Apply to dataset

In [14]:
# define input data
data = [[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0]]
data = asarray(data)
data = data.reshape(1, 8, 8, 1)

print(data)

[[[[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]]]


In [15]:
# create model
model = Sequential()
model.add(Conv2D(1, (3,3), input_shape=(8, 8, 1)))

In [21]:
# define a vertical line detector
detector = [[[[0]],[[1]],[[0]]],
            [[[0]],[[1]],[[0]]],
            [[[0]],[[1]],[[0]]]]

weights = [asarray(detector), asarray([0.0])]

# store the weights in the model
model.set_weights(weights)

# confirm they were stored
print(model.get_weights())

[array([[[[0.]],

        [[1.]],

        [[0.]]],


       [[[0.]],

        [[1.]],

        [[0.]]],


       [[[0.]],

        [[1.]],

        [[0.]]]], dtype=float32), array([0.], dtype=float32)]


In [17]:
# apply filter to input data
yhat = model.predict(data)

In [18]:
for r in range(yhat.shape[1]):
	# print each column in the row
	print([yhat[0,r,c,0] for c in range(yhat.shape[2])])

[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
